package com.initiboard.api.dto;

import java.util.List;

// Pass usages and token generated by BlockService to BlockController
public record BlockUsageResult(
        List<BlockUsageResponse> usages,
        String deletionConfirmationToken
) {
}
